### PR TITLE
refactor registration forms to work with twig templates

### PR DESCRIPTION
**Pull request by russelltsherman**
this is work in progress.. 

an early preview of my approach for review and comment

raw html isn't very DRY or elegant but i think it's the fastest approach to getting working forms

### CODE REVIEW

**Review by pboyd04 — APPROVED** [review]
Yeah I don't think it's the ideal approach. I'm pretty sure you would agree with that. But for now working is better than elegant.

**Comment by russelltsherman** [comment]
i certainly agree that is is not the ideal approach.. 
but I imagine we disagree slightly as to specifically why it is not ideal.

here are my thoughts on what i think the ideal approach would be.

i believe the goal of using templates is to allow less technical individuals to the modify the forms.
truly facilitating that would require a less engineered and less elegant implementation.

ideally the entire form would be contained in a single html page and it would include the least complex template syntax required to do the job.

what we currently have, while i feel it is a step in the right direction, is only slightly less obfuscated than what existed before.. so it falls short of the previously stated goal.

**Comment by treg** [comment]
Take a look at JsonForms.
Specifically the vanilla renderer.

https://jsonforms.io/


My .02

**Comment by russelltsherman** [comment]
json driven forms could be a very elegant and easily manageable solution.

the caveat being that we would be requiring a specialised level of knowledge for the individuals editing the forms.

@treg how has your experience been using json forms? 
have you created complex forms using it?
i.e. ( our camp reg form copies contact info across all contact types when a user clicks the 'i am the only contact' checkbox? )

**Comment by treg** [comment]
JsonForms uses redux so that kind of logic would need to be in a middleware
handler.

**Comment by russelltsherman** [comment]
so using this specific this tool means rewriting our registration form system using react or angular?

**Comment by treg** [comment]
To use jsonforms.io, yes.

The other option would be to use motzilla's version of json forms which
uses plain javascript handling.

**Comment by pboyd04** [comment]
Yeah, I don't think we are that far off. I lean towards something like the json forms approach with middleware or client side script handling the translation rather than plain HTML only because with plain HTML there are a lot of variables to make sure a user fixes in a copy paste situation or does right if they create the plain HTML.

**Pull request merged**
